Add background
lagdush/CodersCamp2021Projekt1 pull request #24
Opened 2021-11-30 17:34 UTC by VivienneSoldier

2021-11-30 18:43 UTC, lagdush requested changes

2021-11-30 18:43 UTC, lagdush commented on style.css
> +  min-width: 100wh;
Here's a typo.

2021-12-01 15:48 UTC, lagdush commented on style.css
>    margin-top: 60px;
Do we need margin here?

2021-12-01 15:53 UTC, lagdush commented
Please delete testComponent

2021-12-01 20:34 UTC, lagdush commented
the background should be centered on each screen
<img width="575" alt="Zrzut ekranu 2021-12-1 o 21 33 29" src="https://user-images.githubusercontent.com/38866668/144309649-27bcfd6e-27d4-4871-bc62-9bd86e4dd321.png">

2021-12-01 20:40 UTC, lagdush commented
the screen shows scroll unnecessarily. Why do you think, could you fix this?

2021-12-01 21:13 UTC, VivienneSoldier commented
> the screen shows scroll unnecessarily. Why do you think, could you fix this?

I think it should be easy to fix it. But now i'm sick, and it's getting worse. I need a little time to cure and to do more with all of this. Its ok to be a bit slower than other (and to talk about this right here xd)?

2021-12-04 08:00 UTC, lagdush requested changes
Delete commented lines of code.

2021-12-04 08:00 UTC, lagdush commented on style.css
> +}
The background on mobile screens is distorted.

2021-12-04 08:00 UTC, lagdush commented on style.css
> +  height: 100vh;
try to delete these values.

2021-12-04 18:50 UTC, lagdush approved these changes

2021-12-05 17:07 UTC, merged